config.toml, content/_index.md, data/featuredstory.yml
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>
=> Create ecdtools contact form

content/news/eclipse-open-vsx-a-free-marketplace-for-vs-code-extensions.md, content/news/eclipse-theia-is-ready-for-primetime.md, content/news/five-things-you-might-not-know-about-eclipse-che.md, content/news/why-eclipse-dirigible-is-ideal-for-cloud-based-development.md
=> Add March 2020 newsletter articles to homepage #15

layouts/shortcodes/home-mission-statement.html
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>
=> Add link to charter on homepage #16

content/news/eclipse-theia-press-release.md
=> Infra 3665 - Add Eclipse Theia Press release to news section

content/initiatives/standard-developer-workspace-definition.md
We merged two initiatives together, this updates makes some minor changes to the external text to match the agreed upon text.
=> Update text for merged initiatives

data/members.yml
=> Remove Intel Corporation From the ECD Tools website #24

content/news/eclipse-foundation-offers-open-source-alternative-to-vs-code.md, content/news/eclipse-theia-is-an-open-source-alternative-to-vs-code.md, content/news/eclipse-theia-offers-a-true-open-source-alternative-to-visual-studio-code.md, content/news/if-you-ever-wished-vs-code-could-be-more-open-source.md, content/news/theia-framework-enables-web-ides.md
=> Add following articles to news section of ECD Tools Website #23

layouts/partials/rss_display.html
=> Updated source of ecdtools RSS feed

layouts/index.html
=> Create a section "Interesting reads" #28

layouts/index.html, layouts/news/section.html, package-lock.json, package.json, static/documents/ecdtools.xml
=> Fix for news_type parameters + loading multiple news types

package-lock.json, package.json, static/documents/ecdtools.xml
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>
=> Update config file for latest theme version

layouts/partials/nav_more.html
=> #46 - Remove More menu from main menu

package-lock.json, package.json, static/documents/ecdtools.xml, webpack.mix.js
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>
=> Add IE 11 support

config.toml, content/community/_index.md
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>
=> Issue #48: New Community page - initial content. Trying again

config.toml, content/projects/_index.md, js/projects.js, layouts/partials/footer_suffix.html, layouts/shortcodes/page-projects.html, package.json, static/mix-manifest.json, webpack.mix.js
Fix #53 
Need improvements:
- categories
- use url to fetch data instead of json
- paging
=> initial trial to add simple project page to list all projects

.travis.yml, Dockerfile, Jenkinsfile, netlify.toml, package-lock.json, package.json
Part of https://github.com/EclipseFdn/hugo-solstice-theme/issues/176
=> Update Hugo and theme to latest

content/_index.md, layouts/shortcodes/home-members.html
Fix #75 
------ Updates ----------
A question from the comment https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/75#issuecomment-743334651
=> update limit of memberships showing on the home page

config.toml, content/adopters/_index.md, content/adopters/how-to-be-listed-as-an-adopter/_index.md, layouts/partials/footer_custom.html, less/styles.less
Fix #42 
is ready, got +1 from Clark and Brian.
=> Adopters Page #42

.travis.yml, Dockerfile, Jenkinsfile, netlify.toml, package-lock.json, package.json
Extended from https://github.com/EclipseFdn/hugo-solstice-theme/issues/191 
=> Update theme to include Anchor feature in adopters page

.travis.yml, Dockerfile, package-lock.json, package.json, webpack.mix.js
=> Update theme to 0.0.111

layouts/index.html
=> Change events section to nearest first

content/events/idesummit/2021/_index.md, data/en/2021/idesummit/registration.yml
=> Update Cloud IDE Day Page for Registration #112

content/events/idesummit/2021/_index.md, data/en/2021/idesummit/agenda.yml, less/styles.less
=> Add Agenda to Cloud IDE Day Page #125

config.toml, content/resources/_index.md
fixed #95
Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>
=> Added resource page

config.toml
For [issue115](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/115)
=> Reordered the menu items

content/events/idesummit/2021/_index.md, data/en/2021/idesummit/agenda.yml
=> Add YouTube Videos and Wrap Up Cloud IDE Day Page #133

layouts/partials/footer_custom.html, layouts/partials/socials.html
=> Add Twitch button to ECD Tools social banner #131

content/resources/_index.md
Fixes [issue137](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/137)
=> Added white papers section

layouts/shortcodes/page/membership.html
=> Updates to the membership page

data/highlights.yml
=> Remove placeholcer text in webinars section

content/resources/blogs/2021-09-15-diagram-editors-web-based-tools-eclipse-glsp.md
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>
=> Add GLSP blog post

less/_components/homepage.less
=> #170 - Fix overlapping images on home page

data/highlights.yml
Fixes [issue177](https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/177)
New request is here: https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/177#issuecomment-961151546
Got +1
=> Updated the description of TheiaCon ad

data/testimonials.yml
fixed #194
Signed-off-by: Jonas Helming <jhelming@eclipsesource.com>
=> Adapted testimonial

package.json, yarn.lock
=> Update hugo theme version

layouts/shortcodes/page/adopters-how-to-be-listed.html
=> #156 - Update content of the Get Listed page

js/src/projects.js, layouts/shortcodes/page/projects.html, less/_components/projects.less
=> #139 - Add filter to Projects page

content/resources/blogs/2022-01-12-theia-cotm/index.md
New blog post.
Signed-off-by: Brian King <brian.king@eclipse-foundation.org>
=> Theia Contributor of the Month Jan 2022

content/resources/blogs/_index.md
Fixes https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/206
=> Added Che blog

less/styles.less
For https://gitlab.eclipse.org/eclipsefdn/it/websites/events.eclipse.org/-/issues/237#note_503732
=> Fixed header img issue for 2021 event

package.json, yarn.lock
For https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/214
=> Removed solstice-assets and updated hugo theme

config.toml, content/_index.md, content/adopters/_index.md
Fixes https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/222
=> Updated the page title shows on browser tabs

layouts/shortcodes/page/resources/community.html
Fixes https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/186
=> Updated twitter hashtags on community page

content/events/cloudideday2022/_index.md
Fixes https://gitlab.eclipse.org/eclipsefdn/it/websites/events.eclipse.org/-/issues/237#note_588865
=> Updated the deadline of call for presentations

content/events/cloudideday2022/_index.md, less/styles.less
For https://gitlab.eclipse.org/eclipsefdn/it/websites/events.eclipse.org/-/issues/237#note_606211
=> Updated the content for CFP section

package.json, yarn.lock
For https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/213#issuecomment-1054382996
=> Updated hugo-theme version

content/resources/blogs/2021-05-11-eclipse-theia-builds-momentum.md, content/resources/blogs/2021-06-25-cloud-ide-day-2021-great-success.md, content/resources/blogs/2021-07-13-5-reasons-to-adopt-eclipse-theia.md, content/resources/blogs/2021-09-15-diagram-editors-web-based-tools-eclipse-glsp.md, content/resources/blogs/2021-10-08-community-update/index.md, content/resources/blogs/2021-11-02-embedded/index.md, content/resources/blogs/2021-12-13-theia-cotm/index.md, content/resources/blogs/2021-12-16-theia-i18n/index.md, content/resources/blogs/2022-01-12-theia-cotm/index.md
Fixes https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/213
https://github.com/EclipseFdn/ecdtools.eclipse.org/issues/213#issuecomment-1067261961
=> Added author info for blogs
